export class Research {
	_id?:string;
	company_Name?:string;
	tin_number?:string;
	company_address?:string;
	tell_number?:string;
	email?:string;
	contact_person?:string;
	area_of_research?:string;
	level_of_research?:string;
	topics_of_research?:string;
	research_time?:string;
	total_research_hour?:string;
	where_delivery_service?:string;
	name_of_researchers?:string;
	transport_provision?:string;
	payable_week_before_research?:string;
	payable_date_request?:string;
	payable_week_after?:string;
	registeration_date?:string;
}
